# #tuple= immutable-values cannot be changed(operations-append,insert,pop,extent,remove,sort cannot be used)
# t=(1,2,3,4,5,6)
# print(t)
# print(t[0])
# print(t[2])
# print(t[4])
# print(t[-1])
# print(t[-2])
# print(t[:3])
# print(t[2:])
# print(t[:4])
# print(t[2:4])
# print(max(t))
# print(min(t))
# print(sum(t))
# print(len(t))
# print(type(t))
# print(dir(t))

t1=(1,1,2,3,4,4,5)
print(t1.count(2))
print(t1.index(3))

