import datetime
from tkinter import *
root=Tk()
root.geometry('1600x700')
root.title('Resturant Mangement System')
topf=Frame(root,bg='white',width=1600,height=50)
topf.pack(side=TOP)
bottomf=Frame(root,bg='red',width=1600,height=50)
bottomf.pack(side=BOTTOM)
f1=Frame(root,width=900,height=600)
f1.pack(side=LEFT)
f2=Frame(root,bg='green',width=600,height=600)
f2.pack(side=RIGHT)
d=datetime.datetime.now()
dblinto=Label(topf,text='Res Manag System',bg='brown',bd=10)
dblinto.grid(row=0,column=1)
dbltime=Label(topf,text=d,bg='steelblue',bd=10)
dbltime.grid(row=1,column=1)
m=IntVar()
m.set('')
f=IntVar()
c=IntVar()
mu=IntVar()
cr=IntVar()
f.set('')
c.set('')
mu.set('')
cr.set('')
o=IntVar()
o.set('')

Label(f1,text='order no').grid(row=0,column=0)
Entry(f1,textvariable=o).grid(row=0,column=1)
Label(f1,text='meals').grid(row=1,column=0)
Entry(f1,textvariable=m).grid(row=1,column=1)
Label(f1,text='fish').grid(row=2,column=0)
Entry(f1,textvariable=f).grid(row=2,column=1)
Label(f1,text='chicken').grid(row=3,column=0)
Entry(f1,textvariable=c).grid(row=3,column=1)
Label(f1,text='mutton').grid(row=4,column=0)
Entry(f1,textvariable=mu).grid(row=4,column=1)
Label(f1,text='crab').grid(row=5,column=0)
Entry(f1,textvariable=cr).grid(row=5,column=1)
Button(f1,text="price").grid(row=6,column=0)
Button(f1,text="total").grid(row=6,column=1)
Button(f1,text="reset").grid(row=6,column=2)
Button(f1,text="exit").grid(row=6,column=3)


root.mainloop()


